-- MySQL Script generated by MySQL Workbench
-- Fri Oct  5 09:16:12 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema survey
-- -----------------------------------------------------
-- 调查

-- -----------------------------------------------------
-- Schema survey
--
-- 调查
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `survey` DEFAULT CHARACTER SET utf8 ;
USE `survey` ;

-- -----------------------------------------------------
-- Table `survey`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `integral` INT NULL DEFAULT 0 COMMENT '积分',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `survey`.`mini_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`mini_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `openid` VARCHAR(255) NULL,
  `nick_name` VARCHAR(45) NULL,
  `avatar_url` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '小程序用户表';


-- -----------------------------------------------------
-- Table `survey`.`survey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`survey` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '调查表';


-- -----------------------------------------------------
-- Table `survey`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `survey_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `type` TINYINT NULL COMMENT '1-单选，2-多选，3-填空',
  `sort` SMALLINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '调查问题表';


-- -----------------------------------------------------
-- Table `survey`.`question_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`question_option` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question_id` INT NOT NULL,
  `content` VARCHAR(255) NULL,
  `poll` INT NULL COMMENT '票数',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '问题选项表';


-- -----------------------------------------------------
-- Table `survey`.`answer_sheet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`answer_sheet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `survey_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '答卷';


-- -----------------------------------------------------
-- Table `survey`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`answer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `answer_sheet_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `answer` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '答题';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
